apiVersion: playlist.grafana.app/v1
kind: Playlist
metadata:
    name: security-monitoring
spec:
    interval: 2m
    items:
        - type: dashboard_by_tag
          value: security
        - type: dashboard_by_uid
          value: auth-failures
        - type: dashboard_by_uid
          value: waf-events
        - type: dashboard_by_tag
          value: audit
        - type: dashboard_by_uid
          value: admsjdg
    title: Security Monitoring
