apiVersion: playlist.grafana.app/v1
kind: Playlist
metadata:
  name: network-observability
  namespace: default
  labels:
    team: network
    domain: networking
spec:
  title: Network Observability
  interval: 1m
  items:
    - type: dashboard_by_tag
      value: network
    - type: dashboard_by_uid
      value: snmp-interfaces
    - type: dashboard_by_uid
      value: cdn-edge-traffic
